### ISSUE TITLE
Espacements non cohérents sur page de mise à jour du profil

### ISSUE THREAD

**Issue by samuelpath** [MTES-MCT/aides-territoires#147]
J'ai le sentiment que la page de mise à jour de profil (`/comptes/profil/`) rendrait mieux si l'espacement entre `Je souhaite recevoir des actualités liées au service.` et `Nous enverrons régulièmement…` était identique à l'espacement entre `Choisissez un nouveau mot de passe` et `Votre mot de passe`.

En l'état, cela donne un aspect d'incohérence, et les 2 lignes de texte semblent trop collées.

Qu'en pensez-vous ?

![image](https://user-images.githubusercontent.com/6030745/90950458-dd081600-e451-11ea-9c32-0567ba77821b.png)

Voici ce que les dev tools révèlent: 

- Pour l'espacement OK

![image](https://user-images.githubusercontent.com/6030745/90976078-65fa7c80-e53a-11ea-90d3-8d8df9fea284.png)

- Pour l'espacement KO

![image](https://user-images.githubusercontent.com/6030745/90976143-def9d400-e53a-11ea-95b3-028e5c0f151d.png)

Dans `_globals.scss`, on a le style suivant : 

```css
form {
    .form-group {
        &.checkbox {
            /*...*/
            label {
                @extend .form-check-label;
            }
           /*...*/
        }

        &>label {
            font-weight: bold;
            margin-bottom: 0;
            margin-bottom: $label-margin-bottom;
        }
/*...*/
}
```

Qui se traduit ainsi dans le CSS compilé : 

```css
.form-check-label, form div.multiple-input div.single-input label, form .form-group.checkbox label {
  margin-bottom: 0;
}
/*...*/
form .form-group > label {
  font-weight: bold;
  margin-bottom: 0;
  margin-bottom: 0.5rem;
}
```

De ce que je comprends, la sélection `form .form-group.checkbox label` récupère la propriété `margin-bottom: 0` du `@extend .form-check-label`.

Les `labels` de `form .form-group.checkbox` ne bénéficient donc pas du `margin-bottom: $label-margin-bottom;` (à savoir `.5rem` par défaut) de `form .form-group > label`, qui est notamment le style appliqué au `label` avec le texte `Choisissez un nouveau mot de passe` plus haut dans le formulaire.

Est-il donc voulu que les `labels` descendants (directs ou indirects) de `form .form-group.checkbox` ne bénéficient pas du `margin-bottom: 0.5rem` censé s'appliquer aux descendants directs de `form .form-group` ?

En d'autres termes, pourquoi souhaiterions-nous une marge de `0.5rem` sous les `labels` des formulaires, mais pas de telle marge pour les `labels` des checkbox de ces mêmes formulaires ?

Pour résoudre cette incohérence, il suffirait de supprimer le style suivant : 

```css
label {
    @extend .form-check-label;
}
```

Ce qui donnerait le résultat suivant : 

![image](https://user-images.githubusercontent.com/6030745/90976289-17e67880-e53c-11ea-9ffa-5c8720a5f098.png)

Mais j'imagine qu'il y a une bonne raison pour laquelle @thibault a rajouté ce `@extend` en premier lieu, dans le commit suivant : a0124fc4f89564bec40d0418399f94eed55eea60, dont le but semble d'ailleurs de rajouter des marges plutôt que d'en enlever (le titre est `Css issue: add margin between following inputs`).

En continuant mon analyse, j'ai trouvé juste un autre élément auquel la sélection `form .form-group.checkbox label` s'applique. Il s'agit du label de checkbox `Cochez cette case s'il s'agit d'un appel à projets (AAP) ou d'un appel à manifestation d'intérêt (AMI)` sur la page https://aides-territoires.beta.gouv.fr/aides/publier/ : 

![image](https://user-images.githubusercontent.com/6030745/90978384-e1b1f480-e54d-11ea-9d0d-e946af6f9ad5.png)

Or, dans ce cas précis, passer le `margin-bottom` de `0` à `0.5rem` comme mon changement suggère n'aurait qu'une différence très peu perceptible : 

Avant le changement : 

![image](https://user-images.githubusercontent.com/6030745/90978433-41a89b00-e54e-11ea-9526-27902cd06fae.png)

Après le changement (l'équivalent du rectangle orange en plus) : 

![image](https://user-images.githubusercontent.com/6030745/90978478-82a0af80-e54e-11ea-8957-ded3b9ce3f31.png)

La différence notable entre le `form .form-group.checkbox label` où le `margin-bottom: 0` pose un problème visuel et celui où il n'y a pas de problème est que l'un a un élément frère en dessous (un `span` de classe `field-help`) tandis que l'autre est le dernier élément de son `div`.

À mon avis, il y aurait du sens à enlever le `margin-bottom` dans le cas d'un label qui est le dernier élément de son `div`, mais de le garder lorsque le label a un élément frère qui le suit (autrement le label et son frère n'ont pas un espacement suffisant).
